name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-port: 27017
          mongodb-version: "8.0"
          mongodb-db: datakolo

      - name: Lint backend
        working-directory: backend
        run: deno run lint

      - name: Generate coverage report
        working-directory: backend
        env:
          TEST_DATABASE_URL: mongodb://localhost:27017/datakolo
        run: deno run coverage-report

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.10
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: backend
          file: ./backend/coverage.lcov

  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup npm
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        working-directory: frontend
        run: npm install

      - name: Lint frontend
        working-directory: frontend
        run: npm run lint

      - name: Run tests with coverage
        working-directory: frontend
        run: npm run coverage

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: frontend/coverage
          flags: frontend
